name: tests

on:
  push:
  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build containers
      run: docker compose build
    - name: Install dependencies
      run: docker compose run -T --rm php-fpm composer install
    - name: Test
      run: docker compose run -T --rm php-fpm composer test-cover-ci
    - name: Upload coverage data to Codecov
      continue-on-error: true
      run: bash <(curl -s https://codecov.io/bash)
